stages:
  split_data:
    cmd: python src/data/data_splitting.py
    deps:
    - src/data/data_splitting.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize_data:
    cmd: python src/data/data_normalization.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/data_normalization.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  grid_search:
    cmd: python models/gridsearch.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/gridsearch.py
    outs:
    - models/best_model.pkl
    - models/best_params.pkl
  train_model:
    cmd: python models/training.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - models/training.py
    outs:
    - models/trained_model.pkl
  evaluate_model:
    cmd: python models/evaluate.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/evaluate.py
    - models/trained_model.pkl
    outs:
    - data/predictions.csv
    - metrics/scores.json
